# Generated by Django 3.1 on 2020-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('user_name', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
